### ISSUE TITLE
Relevance sort direction

### ISSUE THREAD

**Issue by DavidAHazra** [haowei01/pytorch-examples#2]
Hi! Thanks for this excellent repo, it's very informative.

I've noticed that in your implementation of LambdaRank (specifically, on line 178) you sort the rank data frame by relevance in ascending order (which is the default for pandas' sort_values function). 
Every other implementation of LambdaRank I've looked at (allRank, tensorflow-LTR) seems to order relevance levels in a descending order - and I'd have to agree with them (since you want higher relevance items towards the front of the array).

Sorry if I've misunderstood. Thanks.

**Comment by jane96** [comment]
I‘ve noticed the same problem.Do you firgue out this problem? Would you give me some hint?

**Comment by DavidAHazra** [comment]
Hi I never got any response from the author but I assume that the other implementations are correct. If you're making your own implementation I would stick with descending order. I'd be happy to help if you have any other questions.

I'm gonna keep the issue open just in case the author responds.

**Comment by sahilm1992** [comment]
HI authors, any updates on the issue?
Is there any reason for keeping it sorted in asc order?

**Comment by haowei01** [comment]
Hi @DavidAHazra @jane96 and @sahilm1992 thanks for pointing out the issue. In deed I should sort using the descending order.
However, the result does not change. I think the main reason is that we should calculate `|deltaNDCG|`, based on https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/MSR-TR-2010-82.pdf 
If Yi and Yj are different, `|deltaNDCG|` is roughly the same even if we sort the reserved way.

I have changed the implementation using
```
rank_order = np.argsort(-rank_df["Y"]) + 1
```
verified that I get similar result compared to before
